name: 'hugo-cos-deploy'
author: 'flyingpot'
description: 'Deploy your Hugo site to Tencent COS, via GitHub Actions, with Arch Linux.'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'arrow-up-circle'  
  color: 'yellow'
inputs:
  secret_id:
    description: 'Tencent cloud SecretId, from: https://console.cloud.tencent.com/cam/capi'
    required: true
  secret_key:
    description: 'Tencent cloud SecretKey, from: https://console.cloud.tencent.com/cam/capi'
    required: true
  bucket:
    description: 'COS bucket name'
    required: true
  region:
    description: 'COS bucket region, detail: https://cloud.tencent.com/document/product/436/6224'
    required: true
  endpoint:
    description: 'https://cloud.tencent.com/document/product/436/10976'
    required: false
